version: "3"
services:
  api:
    build: .
    ports:
    - "5000:5000"
    volumes:
      - .:/app
    entrypoint: ["python", "api/app.py"]
    depends_on:
    - db

  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432